apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: job-cleaner
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: job-cleaner
            image: registry.gitlab.com/precmed/deployment/kubernetes-job-cleaner
            env:
            - name: NAMESPACE
              value: 'default'
            - name: CLEANUP_THRESHOLD
              value: '100'
          restartPolicy: Never
